name: CI

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ“¥ Checkout repository
        uses: actions/checkout@v4

      - name: ğŸš§ Logseq Publish
        uses: MuhangHE/logseq-publish@main

      - name: ğŸ“„ Add .nojekyll file
        run: touch $GITHUB_WORKSPACE/www/.nojekyll

      # Optional: upload build artifacts (can be used for debugging)
      - name: ğŸ—ƒï¸ Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: published-site
          path: www

      - name: ğŸš€ Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.5.0
        with:
          branch: gh-pages
          folder: www
          clean: true
          single-commit: true
